# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-08 18:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id_back',
        ),
        migrations.RemoveField(
            model_name='user',
            name='id_front',
        ),
        migrations.RemoveField(
            model_name='user',
            name='note',
        ),
    ]
