# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-06 00:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='logo',
            field=models.URLField(unique=True),
        ),
        migrations.AlterField(
            model_name='currency',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default=1, max_length=10),
        ),
    ]
