# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-21 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0003_auto_20170906_0056'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='fees',
            field=models.DecimalField(decimal_places=8, default=2.0, max_digits=16),
        ),
    ]
