# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-22 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0005_auto_20180122_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='fees',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=16),
        ),
    ]
