# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-20 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manualdeposit',
            name='ref_code',
            field=models.CharField(default='BTB4T9DC0', editable=False, max_length=250),
        ),
    ]
