# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-19 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_auto_20180916_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manualdeposit',
            name='ref_code',
            field=models.CharField(default='BTBFQZXP3', editable=False, max_length=250),
        ),
    ]
