# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-05 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_auto_20180920_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manualdeposit',
            name='ref_code',
            field=models.CharField(default='BTBJ273OB', editable=False, max_length=250),
        ),
    ]
