# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-20 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('website_url', models.URLField(max_length=120, null=True)),
                ('logo_url', models.URLField(max_length=250)),
                ('voucher_length', models.IntegerField(default=0)),
            ],
        ),
    ]
