# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-19 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessunit',
            name='voucher_length',
            field=models.IntegerField(default=0),
        ),
    ]
