# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-10 02:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('currency', '0003_auto_20170906_0056'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_needed', models.DecimalField(decimal_places=2, max_digits=6)),
                ('amount_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('reference_id', models.CharField(max_length=256, unique=True)),
                ('receiving_address', models.CharField(default='', max_length=256)),
                ('payment_method', models.CharField(blank=True, choices=[('mobile_money', 'MOBILEMONEY'), ('bank', 'BANK')], default='', max_length=256, null=True)),
                ('transaction_id', models.CharField(blank=True, default='', max_length=256, null=True)),
                ('status', models.CharField(choices=[('pending', 'PENDING'), ('processing', 'PROCESSING'), ('completed', 'COMPLETED'), ('cancelled', 'CANCELLED'), ('flagged', 'FLAGGED')], default='pending', max_length=12)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='currency.Currency')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
