# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-10 03:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyorder',
            name='amount_to_pay',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='buyorder',
            name='amount_needed',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
