# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-11 04:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20170910_0328'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyOrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(default='', max_length=20)),
                ('network_name', models.CharField(default='', max_length=20)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='buyorder',
            name='amount_paid',
        ),
        migrations.RemoveField(
            model_name='buyorder',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='buyorder',
            name='transaction_id',
        ),
        migrations.AddField(
            model_name='buyorderdetail',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='orders.BuyOrder'),
        ),
    ]
