# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-20 12:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20170920_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellorder',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selling_currency', to='currency.Currency'),
        ),
    ]
