# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-01 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_auto_20170920_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyorder',
            name='transaction_phone',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
