# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-22 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_buyorder_transaction_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyorder',
            name='bank_account_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='buyorder',
            name='bank_account_number',
            field=models.IntegerField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='sellorder',
            name='bank_account_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sellorder',
            name='bank_account_number',
            field=models.IntegerField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='sellorder',
            name='bank_branch',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
