# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-22 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_auto_20171122_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyorder',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
    ]
