# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-22 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_auto_20171122_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyorder',
            name='bank_account_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='sellorder',
            name='bank_account_number',
            field=models.IntegerField(null=True),
        ),
    ]
