# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-22 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_auto_20171122_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyorder',
            name='network_name',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sellorder',
            name='network_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sellorder',
            name='phone_number',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
