# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-22 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_auto_20171122_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyorder',
            name='network_name',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
