# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-21 18:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_auto_20171122_2027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sellorder',
            old_name='bank_account_name',
            new_name='bank_name',
        ),
    ]
