# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-07-14 01:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_auto_20180128_1650'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyorder',
            old_name='amount_needed',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='buyorder',
            old_name='currency',
            new_name='coin',
        ),
        migrations.RenameField(
            model_name='buyorder',
            old_name='amount_to_pay',
            new_name='cost',
        ),
        migrations.RemoveField(
            model_name='buyorder',
            name='amount_paid',
        ),
        migrations.RemoveField(
            model_name='buyorder',
            name='bank_account_name',
        ),
        migrations.RemoveField(
            model_name='buyorder',
            name='bank_account_number',
        ),
        migrations.RemoveField(
            model_name='buyorder',
            name='network_name',
        ),
        migrations.RemoveField(
            model_name='buyorder',
            name='receiving_address',
        ),
        migrations.RemoveField(
            model_name='buyorder',
            name='status',
        ),
        migrations.RemoveField(
            model_name='buyorder',
            name='transaction_phone',
        ),
        migrations.AddField(
            model_name='buyorder',
            name='address',
            field=models.CharField(default=' ', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='buyorder',
            name='transaction_id',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='buyorder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
