# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-07-17 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_auto_20180714_0113'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyorder',
            name='fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
