# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-07-17 10:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_buyorder_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyorder',
            name='transaction_id',
            field=models.CharField(max_length=256),
        ),
    ]
